stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."

test_job:
  stage: test
  script:
    - echo "Running tests..."
    # Comandos de teste aqui

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Comandos de deploy aqui
